### ISSUE TITLE
Hidden Component

### ISSUE THREAD

**Issue by matthewwolfe** [bedrock-ui/bedrock-ui#20]
```jsx
<Hidden on="mobile">{children}</Hidden>

<Hidden on={["mobile", "desktop"]}>{children}</Hidden>
```

**Comment by Shajansheriff** [comment]
API suggestion for the <Hidden /> component. 

`<Hidden on="mobile">{children}</Hidden>`

`<Hidden on=["mobile", "desktop"]>{children}</Hidden>`

or 

`<Hide on=["mobile", "desktop"]>{children}</Hidden>`


My thought process behind suggesting this API is that the component name (Hidden) clearly says what it'll do which is hide the children. `on` which breakpoint or device you want to hide is a prop that we can give control to the developer.

**Comment by rutvikshah28** [comment]
> My thought process behind suggesting this API is that the component name (Hidden) clearly says what it'll do which is hide the children. `on` which breakpoint or device you want to hide is a prop that we can give control to the developer.

I agree with the thought process behind using `on`. It seems easier to understand and conveys the use case/s very clearly. Is there a reason behind the initial `hide={{...}}` structuring or was that just an initial thought? 

I haven't done open source contributions and I stumbled upon this, feel free to educate me on the norms, please!

Also, the project seems cool, I'd like to help if possible

**Comment by matthewwolfe** [comment]
@Shajansheriff @rutvikshah28 I like the suggestion for the string + array combinations:

```jsx
<Hidden on="mobile">{children}</Hidden>

<Hidden on={["mobile", "desktop"]}>{children}</Hidden>
```

There will need to be modifications made to the Sass breakpoint output to support that. Right now the Sass breakpoints are calculated as `min-width` only and are stacked on each other, so if a breakpoint value is omitted, the lower breakpoint value will be applied. Although in this case we only want to apply `hidden` at the breakpoints specified in the array, so there will need to be `min-width` **and** `max-width` calculations in the Sass media queries.
