### ISSUE TITLE
Docs: Buttons variants misspelling

### ISSUE THREAD

**Issue by joaosantos99** [bedrock-ui/bedrock-ui#32]
## Description

Both the "Text" and the "Square" buttons, have the same `outlined` as a varaint.

## Screenshot

![Captura de ecrã 2023-02-09 203434](https://user-images.githubusercontent.com/68588265/217931506-f425ed90-ee5b-49c5-9a50-de3759d0fa52.png)

**Comment by matthewwolfe** [comment]
Thanks for submitting an issue! This has been fixed in the latest deploy of the documentation.
